apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  type: NodePort
  ports:
    - name: http
      port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 32432
  selector:
    app: postgres