apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v1
    app: postgres
    team: cartao-branco
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        version: v1
    spec:
      containers:
        - image: postgres:10.4
          imagePullPolicy: Always
          env:
            - name: DATABASE_USER
              value: "keycloak"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_DB
              value: "keycloak"
            - name: DATABASE_HOST
              value: "postgres"
            - name: DATABASE_PORT
              value: "5432" 
          resources:
            requests:
              memory: "256Mi"
              cpu: "700m"
            limits:
              memory: "512Mi"
              cpu: "900m"
          name: postgres
          ports:
            - containerPort: 5432
              name: http
              protocol: TCP
