apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v1
    app: prometheus
    team: cartao-branco
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        version: v1
    spec:
      containers:
        - image: prom/prometheus
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "700m"
            limits:
              memory: "512Mi"
              cpu: "900m"
          name: prometheus
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
